# Generated by Django 5.0.7 on 2025-08-27 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
    ]
